Workout.delete_all
Exercise.delete_all
Session.delete_all
User.delete_all
WorkoutExercise.delete_all
UserSession.delete_all
SessionWorkout.delete_all
UserSessionWorkoutExercise.delete_all




# Users are users 
User.create(name: "Thompson", email: "thompson@thompsonplyler.com", password: "password")
User.create(name: "Joann", email: "joannlpan@gmail.com", password: "password")
thompson = User.find_by(name: "Thompson")


# Sessions correspond to days of the program. A session is a day at the gym. 
Session.create(day: 1, name: "Foundational Power A, Session 1")
Session.create(day: 2, name: "Movement Day")
Session.create(day: 3, name: "Foundational Power B, Session 1")
Session.create(day: 4, name: "Movement Day")
Session.create(day: 5, name: "Foundational Power A, Session 2")
Session.create(day: 6, name: "Regeneration Day")
Session.create(day: 7, name: "Foundational Power B, Session 2")
Session.create(day: 8, name: "Movement Day")
Session.create(day: 9, name: "Foundational Power A, Session 3")
Session.create(day: 10, name: "Movement Day")
Session.create(day: 11, name: "Foundational Power A, Session 3")
Session.create(day: 12, name: "Regeneration Day")
Session.create(day: 13, name: "Power 1A, Session 1")
Session.create(day: 14, name: "Movement Day")
Session.create(day: 15, name: "Power 1B, Session 1")
Session.create(day: 16, name: "Movement Day")
Session.create(day: 17, name: "Power 1C, Session 1")
Session.create(day: 18, name: "Regeneration Day")
Session.create(day: 19, name: "Power 1A, Session 2")
Session.create(day: 20, name: "Movement Day")
Session.create(day: 21, name: "Power 1B, Session 2")
Session.create(day: 22, name: "Movement Day")
Session.create(day: 23, name: "Power 1C, Session 2")
Session.create(day: 24, name: "Regeneration Day")
Session.create(day: 25, name: "Power 1A, Session 3")
Session.create(day: 26, name: "Movement Day")
Session.create(day: 27, name: "Power 1B, Session 3")
Session.create(day: 28, name: "Movement Day")
Session.create(day: 29, name: "Power 1C, Session 3")
Session.create(day: 30, name: "Regeneration Day")
Session.create(day: 31, name: "Foundational Power A, Session 1")
Session.create(day: 32, name: "Movement Day")
Session.create(day: 33, name: "Foundational Power B, Session 1")
Session.create(day: 34, name: "Movement Day")
Session.create(day: 35, name: "Foundational Power A, Session 2")
Session.create(day: 36, name: "Regeneration Day")
Session.create(day: 37, name: "Foundational Power B, Session 2")
Session.create(day: 38, name: "Movement Day")
Session.create(day: 39, name: "Foundational Power A, Session 3")
Session.create(day: 40, name: "Movement Day")
Session.create(day: 41, name: "Foundational Power A, Session 3")
Session.create(day: 42, name: "Regeneration Day")
Session.create(day: 43, name: "Power 2A, Session 1")
Session.create(day: 44, name: "Movement Day")
Session.create(day: 45, name: "Power 2B, Session 1")
Session.create(day: 46, name: "Movement Day")
Session.create(day: 47, name: "Power 2C, Session 1")
Session.create(day: 48, name: "Regeneration Day")
Session.create(day: 49, name: "Power 2A, Session 2")
Session.create(day: 50, name: "Movement Day")
Session.create(day: 51, name: "Power 2B, Session 2")
Session.create(day: 52, name: "Movement Day")
Session.create(day: 53, name: "Power 2C, Session 2")
Session.create(day: 54, name: "Regeneration Day")
Session.create(day: 55, name: "Power 2A, Session 3")
Session.create(day: 56, name: "Movement Day")
Session.create(day: 57, name: "Power 2B, Session 3")
Session.create(day: 58, name: "Movement Day")
Session.create(day: 59, name: "Power 2C, Session 3")
Session.create(day: 60, name: "Regeneration Day")
Session.create(day: 61, name: "Foundational Power A, Session 1")
Session.create(day: 62, name: "Movement Day")
Session.create(day: 63, name: "Foundational Power B, Session 1")
Session.create(day: 64, name: "Movement Day")
Session.create(day: 65, name: "Foundational Power A, Session 2")
Session.create(day: 66, name: "Regeneration Day")
Session.create(day: 67, name: "Foundational Power B, Session 2")
Session.create(day: 68, name: "Movement Day")
Session.create(day: 69, name: "Foundational Power A, Session 3")
Session.create(day: 70, name: "Movement Day")
Session.create(day: 71, name: "Foundational Power A, Session 3")
Session.create(day: 72, name: "Regeneration Day")
Session.create(day: 73, name: "Power 3A, Session 1")
Session.create(day: 74, name: "Movement Day")
Session.create(day: 75, name: "Power 3B, Session 1")
Session.create(day: 76, name: "Movement Day")
Session.create(day: 77, name: "Power 3C, Session 1")
Session.create(day: 78, name: "Regeneration Day")
Session.create(day: 79, name: "Power 3A, Session 2")
Session.create(day: 80, name: "Movement Day")
Session.create(day: 81, name: "Power 3B, Session 2")
Session.create(day: 82, name: "Movement Day")
Session.create(day: 83, name: "Power 3C, Session 2")
Session.create(day: 84, name: "Regeneration Day")
Session.create(day: 85, name: "Power 3A, Session 3")
Session.create(day: 86, name: "Movement Day")
Session.create(day: 87, name: "Power 3B, Session 3")
Session.create(day: 88, name: "Movement Day")
Session.create(day: 89, name: "Power 3C, Session 3")
Session.create(day: 90, name: "Regeneration Day")
Session.create(day: 91, name: "Foundational Power A, Session 1")
Session.create(day: 92, name: "Movement Day")
Session.create(day: 93, name: "Foundational Power B, Session 1")
Session.create(day: 94, name: "Movement Day")
Session.create(day: 95, name: "Foundational Power A, Session 2")
Session.create(day: 96, name: "Regeneration Day")
Session.create(day: 97, name: "Foundational Power B, Session 2")
Session.create(day: 98, name: "Movement Day")
Session.create(day: 99, name: "Foundational Power A, Session 3")
Session.create(day: 100, name: "Movement Day")
Session.create(day: 101, name: "Foundational Power A, Session 3")
Session.create(day: 102, name: "Regeneration Day")
Session.create(day: 103, name: "Power 4A, Session 1")
Session.create(day: 104, name: "Movement Day")
Session.create(day: 105, name: "Power 4B, Session 1")
Session.create(day: 106, name: "Movement Day")
Session.create(day: 107, name: "Power 4C, Session 1")
Session.create(day: 108, name: "Regeneration Day")
Session.create(day: 109, name: "Power 4A, Session 2")
Session.create(day: 110, name: "Movement Day")
Session.create(day: 111, name: "Power 4B, Session 2")
Session.create(day: 112, name: "Movement Day")
Session.create(day: 113, name: "Power 4C, Session 2")
Session.create(day: 114, name: "Regeneration Day")
Session.create(day: 115, name: "Power 4A, Session 3")
Session.create(day: 116, name: "Movement Day")
Session.create(day: 117, name: "Power 4B, Session 3")
Session.create(day: 118, name: "Movement Day")
Session.create(day: 119, name: "Power 4C, Session 3")
Session.create(day: 120, name: "Regeneration Day")

day_1 = Session.find_by(name: "Foundational Power A, Session 1")
day_15 = Session.find_by(day: 15)

thompson_day1 = UserSession.create(session_id: day_1.id, user_id: thompson.id)

# A workout is a section of a session. Workouts can be shared between sessions. 
Workout.create(component: "Pillar Prep", name: "Day 1 - Pillar Prep")
Workout.create(component: "Movement Prep", name: "Day 1 - Movement Prep")
Workout.create(component: "Plyometrics", name: "Day 1 - Plyometrics")
Workout.create(component: "Medicine Ball", name: "Day 1 - Medicine Ball")
Workout.create(component: "Relative Power", name: "Day 1 - Total Body Power")
Workout.create(component: "Relative Power", name: "Day 1 - Primary Power")
Workout.create(component: "Relative Power", name: "Day 1 - Secondary Power")
Workout.create(component: "Relative Power", name: "Day 1 - Rotational Power")
Workout.create(component: "ESD", name: "Day 1 - ESD")
Workout.create(component: "Movement Skills", name: "Movement Skills - Multidirectional")
Workout.create(component: "Movement Skills", name: "Movement Skills - Linear")
Workout.create(component: "Movement Skills", name: "Movement Skills - Combination")
Workout.create(component: "Regeneration", name: "Regeneration - General")
Workout.create(component: "Regeneration", name: "Regeneration - Hip pain")
Workout.create(component: "Regeneration", name: "Regeneration - Flexibility")
Workout.create(component: "Regeneration", name: "Regeneration - Knee Pain")
Workout.create(component: "Regeneration", name: "Regeneration - Upper Back/Shoulder Pain")
Workout.create(component: "Regeneration", name: "Regeneration - Self Massage")
Workout.create(component: "Regeneration", name: "Regeneration - Hip Pain")

SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Pillar Prep")).id, order: 1)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, order: 2)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Plyometrics")).id, order: 3)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Total Body Power")).id, order: 4)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Primary Power")).id, order: 5)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Secondary Power")).id, order: 6)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - Rotational Power")).id, order: 7)
SessionWorkout.create(session_id: (Session.find_by(day: 1)).id, workout_id: (Workout.find_by(name:"Day 1 - ESD")).id, order: 8)

Exercise.create(name: "Overhead Rotational Squat - 1 Arm Kettlebell", description: "Poop", category: "rep_weight", bi: true)
Exercise.create(name: "Lateral Pillar Bridge to Row w/ Hip Flexion", description: "Bloop", category: "rep_weight", bi: true)
Exercise.create(name: "Deep Squat to Hamstring Stretch", description: "Shoop", category: "rep_null", bi: true)
Exercise.create(name: "Foam Roll - Glutes", description: "", category: "duration", bi: true)
Exercise.create(name: "Foam Roll - IT Band", description: "", category: "duration", bi: true)
Exercise.create(name: "Foam Roll - Quadriceps", description: "", category: "duration", bi: true)
Exercise.create(name: "Foam Roll - Latissimus Dorsi", description: "", category: "duration", bi: true)
Exercise.create(name: "Trigger Point - Arch/Plantar Fascia", description: "", category: "rep_null", bi: true)
Exercise.create(name: "Inverted Hamstring", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Knee Hug", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Reverse Lunge - Forearm to Instep with Rotation", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Lateral Lunge", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Pillar March - Linear", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Pillar March - Skip", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Drop Squat - 2 Foot to 1 Foot", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Linear Hurdle Hop - Countermovement", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Lateral Bound - Stabilize (Miniband)", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Bench Press, Alternating DB w/ Leg Lowering", description: "", category: "rep_weight", bi:true)
Exercise.create(name: "Sliding Overhead Press", description: "", category: "rep_null", bi:true)
Exercise.create(name: "RDL to Row - 1 Arm, 1 Leg (cable)", description: "", category: "rep_weight", bi:true)
Exercise.create(name: "Inverted Hamstring Stretch w/ Rotation", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Pull-up, 3 Point Isometric Holds", description: "", category: "duration", bi:true)
Exercise.create(name: "Trigger Point - Thoracic Spine", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Split Squat - 1 Arm", description: "", category: "rep_weight", bi:true)
Exercise.create(name: "Quad Hip Flexor Stretch - Half Kneeling", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Stability Chop - Half Kneeling (cable)", description: "", category: "rep_weight", bi:true)
Exercise.create(name: "Dynamic Pillar Bridge (TRX)", description: "", category: "rep_null", bi:true)
Exercise.create(name: "Kettlebell Shoulder Press w/ Lateral Flexion", description: "", category: "rep_weight", bi:true)
Exercise.create(name: "ESD Machine - Hard", description: "", category: "speed", bi:true)
Exercise.create(name: "ESD Machine - Medium", description: "", category: "speed", bi:true)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Pillar Prep")).id, exercise_id: (Exercise.find_by(name:"Foam Roll - Glutes")).id, reps: 30, set: 1, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Pillar Prep")).id, exercise_id: (Exercise.find_by(name:"Foam Roll - IT Band")).id, reps: 30, set: 1, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Pillar Prep")).id, exercise_id: (Exercise.find_by(name:"Foam Roll - Quadriceps")).id, reps: 30, set: 1, order: 3)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Pillar Prep")).id, exercise_id: (Exercise.find_by(name:"Foam Roll - Latissimus Dorsi")).id, reps: 30, set: 1, order: 4)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Pillar Prep")).id, exercise_id: (Exercise.find_by(name:"Trigger Point - Arch/Plantar Fascia")).id, reps: 50, set: 1, order: 5)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, exercise_id: (Exercise.find_by(name:"Inverted Hamstring")).id, reps: 5, set: 1, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, exercise_id: (Exercise.find_by(name:"Knee Hug")).id, reps: 5, set: 1, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, exercise_id: (Exercise.find_by(name:"Reverse Lunge - Forearm to Instep with Rotation")).id, reps: 5, set: 1, order: 3)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, exercise_id: (Exercise.find_by(name:"Lateral Lunge")).id, reps: 5, set: 1, order: 4)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, exercise_id: (Exercise.find_by(name:"Pillar March - Linear")).id, reps: 10, set: 2, order: 5)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Movement Prep")).id, exercise_id: (Exercise.find_by(name:"Pillar March - Skip")).id, reps: 10, set: 3, order: 6)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Plyometrics")).id, exercise_id: (Exercise.find_by(name:"Drop Squat - 2 Foot to 1 Foot")).id, reps: 6, set: 2, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Plyometrics")).id, exercise_id: (Exercise.find_by(name:"Linear Hurdle Hop - Countermovement")).id, reps: 6, set: 2, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Plyometrics")).id, exercise_id: (Exercise.find_by(name:"Lateral Bound - Stabilize (Miniband)")).id, reps: 6, set: 3, order: 3)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Total Body Power")).id, exercise_id: (Exercise.find_by(name:"Overhead Rotational Squat - 1 Arm Kettlebell")).id, reps: 9, set: 2, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Total Body Power")).id, exercise_id: (Exercise.find_by(name:"Deep Squat to Hamstring Stretch")).id, reps: 6, set: 2, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Total Body Power")).id, exercise_id: (Exercise.find_by(name:"Lateral Pillar Bridge to Row w/ Hip Flexion")).id, reps: 6, set: 2, order: 3)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Primary Power")).id, exercise_id: (Exercise.find_by(name:"Bench Press, Alternating DB w/ Leg Lowering")).id, reps: 8, set: 3, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Primary Power")).id, exercise_id: (Exercise.find_by(name:"Sliding Overhead Press")).id, reps: 6, set: 3, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Primary Power")).id, exercise_id: (Exercise.find_by(name:"RDL to Row - 1 Arm, 1 Leg (cable)")).id, reps: 8, set: 3, order: 3)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Primary Power")).id, exercise_id: (Exercise.find_by(name:"Inverted Hamstring Stretch w/ Rotation")).id, reps: 6, set: 3, order: 4)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Secondary Power")).id, exercise_id: (Exercise.find_by(name:"Pull-up, 3 Point Isometric Holds")).id, reps: 10, set: 3, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Secondary Power")).id, exercise_id: (Exercise.find_by(name:"Trigger Point - Thoracic Spine")).id, reps: 5, set: 3, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Secondary Power")).id, exercise_id: (Exercise.find_by(name:"Split Squat - 1 Arm")).id, reps: 8, set: 3, order: 3)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Secondary Power")).id, exercise_id: (Exercise.find_by(name:"Quad Hip Flexor Stretch - Half Kneeling")).id, reps: 6, set: 3, order: 4)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Rotational Power")).id, exercise_id: (Exercise.find_by(name:"Pull-up, 3 Point Isometric Holds")).id, reps: 8, set: 3, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Rotational Power")).id, exercise_id: (Exercise.find_by(name:"Trigger Point - Thoracic Spine")).id, reps: 10, set: 3, order: 2)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - Rotational Power")).id, exercise_id: (Exercise.find_by(name:"Split Squat - 1 Arm")).id, reps: 8, set: 3, order: 3)

WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - ESD")).id, exercise_id: (Exercise.find_by(name:"ESD Machine - Hard")).id, reps: 30, set: 1, order: 1)
WorkoutExercise.create(workout_id: (Workout.find_by(name:"Day 1 - ESD")).id, exercise_id: (Exercise.find_by(name:"ESD Machine - Medium")).id, reps: 270, set: 1, order: 2)











